global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081'] # 리눅스 호스트의 8081 포트로 WAS 연결

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'localhost:3307' # chat-be의 application.yml DB 포트에 맞춤
