# src/main/resources/application.yml

allowed-origins: http://localhost:5173

server:
  port: 8080
  servlet:
    session:
      timeout: 60m

spring:
  #--- 데이터베이스 설정 ---
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/chatdb?useUnicode=true&characterEncoding=utf8
    username: chat_user # DB 사용자 이름
    password: chat_pwd # DB 비밀번호

  #--- JPA 설정 ---
  jpa:
    hibernate:
      ddl-auto: validate # 애플리케이션 실행 시 엔티티 변경사항을 DB에 자동 반영
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅
    show-sql: true # 실행되는 SQL 쿼리를 로그로 출력

#--- JWT 설정 ---
jwt:
  secret: VeryVeyrVeryVeryVeryVeryVeryVeryVeryVeryVeryLongAndSecureSecretKeyForJWT # 256비트 이상의 시크릿 키

#--- CORS 설정 (React 앱 포트가 3000일 경우) ---
cors:
  allowed-origins: http://localhost:3000